FROM nginx:alpine
ENV VUE_APP_UPLOAD_URL=http://stormspotter-backend:9090/api/upload

RUN adduser -u 1000 -D -S -G www-data www-data

COPY dist/spa /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
