NODE_LABELS = [
    ["AADApplication", "url(../assets/images/aadapp.png)"],
    ["AADGroup", "url(../assets/images/aadgroup.png)"],
    ["AADServicePrincipal", "url(../assets/images/aadsp.png)"],
    ["AADUser",  "url(../assets/images/aaduser.png)"],
    ["Disk", "url(../assets/images/disks.png)"],
    ["GenericAsset", "url(../assets/images/generic.png)"],
    ["IpConfiguration", "url(../assets/images/ipconf.png)"],
    ["KeyVault", "url(../assets/images/kv.png)"],
    ["LoadBalancer", "url(../assets/images/loadb.png)"],
    ["NetworkInterface", "url(../assets/images/nic.png)"],
    ["NetworkSecurityGroup", "url(../assets/images/nsg.png)"],
    ["PublicIp", "url(../assets/images/ip.png)"],
    ["ResourceGroup", "url(../assets/images/rg.png)"],
    ["Rule", "url(../assets/images/rule.png)"],
    ["ServiceFabric", "url(../assets/images/sf.png)"],
    ["ServerFarm", "url(../assets/images/serverfarm.png)"],
    ["SQLDatabase", "url(../assets/images/sqldb.png)"],
    ["SQLServer", "url(../assets/images/sqlserver.png)"],
    ["StorageAccount", "url(../assets/images/storage.png)"],
    ["Subscription", "url(../assets/images/sub.png)"],
    ["Tenant", "url(../assets/images/tenant.png)"],
    ["VirtualMachine", "url(../assets/images/vm.png)"],
    ["VirtualNetwork", "url(../assets/images/vnet.png)"],
    ["WebSite", "url(../assets/images/appservice.png)"],
]